import LocalizedStrings from 'react-native-localization'

/**
 * Localization
 */
let strings = new LocalizedStrings({
    "en-US": {
        ok: "Ok",
        cancel: "Cancel",
        emailId: "Email ID",
        password: "Password",
        forgotPassword: "Forgot Password?",
        sign_in: "Sign in",
        new_entrepreneur: "New Entrepreneur?",
        sign_up: "Contact Us",
        mein_promotions: "My Promotions",
        purchase: "Purchase",
        purchases: "Purchases",
        my_area: "My Area",
        hot_deals: "Hot Deals",
        actions: "Gastro, Dienste & Co.",
        events: "Events, Workshops & Co.",
        view_all: "View All",
        messenger: "Messenger",
        my_appointments: "My Appointments",
        appointments: "Appointments",
        profile: "Profile",
        first_name: "First Name",
        last_name: "Last Name",
        confirm_password: "Confirm Password",
        mobile_number: "Mobile Number",
        back_to_login: "Back to sign in",
        back: "Back",
        asterisk: "*",
        internet_not_connected: "Internet not connected. Please check your network connection and try again later.",
        something_went_wrong: "There is connectivity issue at present, please try after sometime.",
        could_not_connect_server: "Could not connect to server, please try again later.",
        enter_email: "Please enter Email ID",
        invalid_email: "Please enter a valid Email ID",
        enter_password: "Please enter Password",
        enter_new_password: "Please enter new Password",
        left: "left",
        euro: "\u20AC",
        send_otp: "Send OTP",
        sort_by_distance: "Sort by Distance",
        filter_by_date: "Filter by Date",
        read_more: "Read more",
        read_less: "Read less",
        message: "Message",
        call: "Call",
        details_and_conditions: "Details & Conditions",
        deal_details_conditions: "Deal Details & Conditions",
        event_details_conditions: "Event Details & Conditions",
        price_list: "Price list",
        done: "Done",
        business_name: "Business Name",
        address: "Address",
        enter_first_name: "Enter First name",
        enter_last_name: "Enter Last name",
        password_should_be: "Password should be minimum of 6 characters",
        enter_confirm_password: "Please enter Confirm Password",
        password_do_not_match: "Password and Confirm Password do not match",
        enter_mobile: "Enter Mobile number",
        mobile_should_be: "Mobile number should be minimum of 7 digits",
        enter_valid_mobile: "Please enter a valid mobile number",
        login_to_continue: "Please login to continue",
        change_password: "Change Password",
        language: "Language",
        sign_out: "Sign out",
        sure_logout_out: "Are you sure you want to logout?",
        yes: "Yes",
        no: "No",
        enter_otp: "Enter OTP",
        submit: "Submit",
        resend_otp: "Resend OTP",
        please_enter_otp: "Please enter OTP",
        otp_should_be: "OTP should be of 4 digits",
        incorrect_otp: "Incorrect OTP",
        old_password: "Old Password",
        new_password: "New Password",
        enter_old_password: "Please enter old password",
        new_password_do_not_match: "New Password and Confirm Password do not match",
        reset_password: "Reset Password",
        password_changed_successfully: "Password changed successfully",
        menu_not_available: "Menu not available",
        english: "English",
        german: "German",
        code: "Code",
        press_back_again_to_exit: "Press back again to exit",
        purchase_id: "Purchase ID",
        coupon_code: "Coupon Code",
        unpublish: "Unpublish",
        publish: "Publish",
        delete: "Delete",
        upcoming: "Upcoming",
        past: "Past",
        active: "Active",
        redeemed: "Redeemed",
        expired: "Expired",
        purchased_on: "Purchase On",
        expires_on: "Expires On",
        settings: "Settings",
        rejected: "Rejected",
        no_of_guests: "Guests",
        date: "Date",
        appointment: "Appointment",
        date_time: "Date & Time",
        approve: "Approve",
        reject: "Reject",
        your_query: "Your Query",
        scan_qr: "Scan QR",
        sync_data: "Sync Data",
        please_scan_qr: "Please scan the QR code to redeem the deal",
        scan_qr_code: "Scan QR Code",
        enter_manually: "Enter Manually",
        pending_data: "Pending Data",
        sync_now: "Sync Now",
        dashboard: "Dashboard",
        or: "or",
        enter_qr_code: "Please enter QR code",
        save: "Save",
        edit: "Edit",
        deal_redeemed_successully: "Deal redeemed successfully",
        deal_code: "Deal Code",
        redeemed_on: "Redeemed on",
        no_data_to_sync: "No data to sync",
        data_synced_successfully: "Data has been synced successfully",
        bonus_cards: "Bonus Cards",
        bonus_card_scanned_successfully: "Bonus card scanned successfully",
        invalid_code: "Invalid code",
        pending_data_exists: "You have pending offline data, please sync it before logout",
        holidays: "My Capacity",
        delete_chat: "Delete",
        sure_delete_chat: "Are you sure you want to delete this message?",
        no_records_found: "No records found",
        filter_by_date: "Sort by Date",
        choose_by_date: "Choose Date",
        sure_delete_holiday: "Are you sure you want to delete this capacity?",
        add_holiday: "Add Capacity",
        date_star: "Date*",
        from_time: "From Time*",
        to_time: "To Time*",
        info: "All Dates",
        days_of_week: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        event_schedule: "Event Schedule",
        this_deal_can_be_redeemed_on_dates: "Redemption Periods",
        from: "From",
        statistics: "Statistics",
        redemption_dates: "Redemption Dates",
        until_stock_lasts: "Until Stock Lasts",
        on_following_days: "always on following days:",
        this_deal_can_be_redeemed: "This deal can redeemed on/before:",
        details: "Details",
        conditions: "Conditions",
        published: "Published",
        unpublished: "Unpublished",
        okay: "Okay",
        Saved: "Saved",
        Booked: "Booked",
        Checked_in: "Checked-in",
        Reedemed: "Reedemed",
        Scanned: "Scanned",
        Clicks: "Clicks",
        error_holiday_mandatory: "Please choose all the mandatory fields",
        error_holiday_from_less_than_to: "Please select FROM time less than To time",
        my_promotions: "My Promotions",
        pending: "Pending",
        guests: "guests",
        guest: "guest",
        deal: "deal",
        deals: "deals",
        no_upcoming_appointments: "No upcoming appointments",
        no_past_appointments: "No past appointments",
        alternate_dates: "Alternate Dates",
        no_pending_appointments: "No pending appointments",
        no_rejected_appointments: "No rejected appointments",
        guests_capital: "Guests",
        deals_capital: "Deals",
        confirm_cancel_appointment: "Are you sure you want to cancel this appointment?",
        time_star: "Time*",
        error_appointment_future_date: "Please select appointment Date & Time in future",
        confirm_approve_appointment: "Are you sure you want to approve this appointment ?",
        confirm_reject_appointment: "Are you sure you want to reject this appointment ?",
        book: "Book",
        alternate_date: "Alternate Date",
        alternate_time: "Alternate Time",
        no_of_deals: "No. of deals",
        sure_unpublish_product: "Are you sure you want to unpublish this product?",
        sure_publish_product: "Are you sure you want to publish this product?",
        promotional_period: "Promotional Periods",
        error_holiday_from_time: "Please choose FROM appointment time",
        error_holiday_date: "Please choose appointment date",
        error_holiday_future: "Please select FROM time in future",
        error_appointment_date: "Please select appointment date",
        error_appointment_time: "Please select appointment time",
        no_hot_deals_found: "No Hot Deals found",
        no_actions_found: "No Actions found",
        no_events_found: "No Events found",
        full_day_off: "Full day off",
        confirm_delete_appointment: "Are you sure you want to delete this appointment?",
        full_day_off: "Full day off",
        product_draft_error: "You can not publish this as there is no image/menu attached. Please attach the image/menu first then publish.",
        add_product: "Add Product",
        select_product:"Select Product",
        holiday_date:"Please choose date",
        holiday_from_time:"Please choose From time",
        holiday_to_time:"Please choose To time",
        bonus_deals: "Bonus Deals",
        no_bonus_deals_found: "No Bonus Deals found",
        available_till: "Available till...",
        scans_required: "scans required",
        fcm_permission_required: "Permission required to receive Push Notifications",
        notifications: "Notifications",
        no_notifications_yet: "No notifications yet",
        confirm_delete_notification: "Are you sure you want to delete this notification?",
        to: "To",
        choose_time_suggested_by_user: "Please choose date & time from suggested times by user",
        add_bonus_conditions: "Bonus deal cannot be published without bonus conditions",
        edit_holiday: "Update Capacity",
        emp_login_not_allowed: "Employee login is not allowed in this app, please download Employee app.",
        clicks_on_info: "Clicks on info",
        booking_requests: "Booking Requests",
        clicks_on_call: "Clicks on Call",
        clicks_on_messenger: "Clicks on Messenger",
        messages: "Messages",
        redirect_to_website: "Redirect to Website",
        secured_deals: "Secured Deals",
        reset: "Reset",
        search: "Search",
        you_have_new_messages_refresh: "You have got new message, please refresh",
        for_what_content: "For what content do you want to block booking requests?",
        block_opening_time: "Block Opening Time",
        block_products: "Block Products",
        complete_block: "Complete Block",
        ent_login_not_allowed: "Entrepreneur login is not allowed in this app, please download Entrepreneur app.",
        send_push_message: "Send Push Message",
        send_push_to_fav_ent: "Send push message to your favorite list",
        send_push_to_fav_product: "Send push message to users who have added the content to their watch list",
        capacity_type: "Capacity Type",
        choose: "Choose",
        predefined_slots: "Predefined Slots",
        percent_discount: "% discount",
        cancelled_by_you: "Cancelled by You",
        cancelled_by_user: "Cancelled by User",
        regular_operation: "Regular Operation",
        your_data_belongs_to_you: "Your data is yours and will only be used to process your request. You can find out more about this in our",
        info_on_data_protection: "Information on data protection",
        submit_request: "Submit Request",
        desired_date: "Desired Date",
        name_of_location: "Name of your Location",
        approved_date: "Meeting",
        confirm: "Confirm",
    },
    "de": {
        ok: "Ok",
        cancel: "Absagen",
        emailId: "E-Mail-Adresse",
        password: "Passwort",
        forgotPassword: "Passwort vergessen?",
        sign_in: "Anmelden",
        new_entrepreneur: "Noch kein Partner?",
        sign_up: "Kontaktiere uns",
        mein_promotions: "Meine Promotions",
        purchase: "",
        purchases: "",
        my_area: "Mein Bereich ",
        hot_deals: "Hot Deals",
        actions: "Gastro, Dienste & Co.",
        events: "Events, Workshops & Co.",
        view_all: "Mehr",
        messenger: "Messenger",
        my_appointments: "Meine Termine",
        appointments: "Termine",
        profile: "Profil",
        first_name: "Vorname",
        last_name: "Nachname",
        confirm_password: "Passwort bestätigen",
        mobile_number: "Telefonnummer",
        back_to_login: "Zurück zur Anmeldung",
        back: "Zurück",
        asterisk: "*",
        internet_not_connected: "Keine Internetverbindung. Bitte überprüfe Deine Netzwerkverbindung und versuche es erneut",
        something_went_wrong: "Keine Verbindung möglich. Bitte versuche es erneut",
        could_not_connect_server: "Keine Verbindung zum Server möglich. Bitte versuche es später erneut",
        enter_email: "Bitte E-Mail-Adresse eingeben",
        invalid_email: "Bitte gib eine gültige E-Mail-Adresse ein",
        enter_password: "Bitte Passwort eingeben",
        enter_new_password: "Bitte neues Passwort eingeben",
        left: "übrig",
        euro: "\u20AC",
        send_otp: "Einmal-Passwort senden",
        sort_by_distance: "Nach Enternung",
        filter_by_date: "Datum wählen",
        read_more: "mehr",
        read_less: "weniger",
        message: "Nachricht",
        call: "Anrufen ",
        details_and_conditions: "Details & Konditionen",
        deal_details_conditions: "Details & Konditionen",
        event_details_conditions: "Details & Konditionen",
        price_list: "Preisliste",
        done: "Fertig",
        business_name: "Firmenname",
        address: "Adresse",
        enter_first_name: "Bitte Vornamen eingeben",
        enter_last_name: "Bitte Nachnamen eingeben",
        password_should_be: "Passwort muss mindestens 6 Zeichen lang sein",
        enter_confirm_password: "Bitte Passwort bestätigen",
        password_do_not_match: "Passwörter stimmen nicht überein",
        enter_mobile: "Bitte Telefonnummer angeben",
        mobile_should_be: "Telefonnummer muss mindestens 7 Zeichen enthalten",
        enter_valid_mobile: "Bitte gib eine gültige Telefonnummer ein",
        login_to_continue: "Zum Fortfahren bitte anmelden",
        change_password: "Passwort ändern",
        language: "Sprache",
        sign_out: "Abmelden",
        sure_logout_out: "Bist Du sicher, dass Du Dich abmelden willst?",
        yes: "Ja",
        no: "Nein",
        enter_otp: "Einmal-Passwort eingeben",
        submit: "Senden",
        resend_otp: "Einmal-Passwort erneut senden",
        please_enter_otp: "Bitte Einmal-Passwort eingeben",
        otp_should_be: "Einmal-Passwort falsch",
        incorrect_otp: "Einmal-Passwort falsch",
        old_password: "Altes Passwort",
        new_password: "Neues Passwort",
        enter_old_password: "Altes Passwort eingeben",
        new_password_do_not_match: "Passwörter stimmen nicht überein",
        reset_password: "Passwort ändern",
        password_changed_successfully: "Passwort erfolgreich geändert",
        menu_not_available: "Preisliste nicht verfügbar",
        english: "Englisch",
        german: "Deutsch",
        code: "Vorwahl",
        press_back_again_to_exit: "Zum Verlassen auf zurück",
        purchase_id: "",
        coupon_code: "Coupon Code",
        unpublish: "Offline setzen",
        publish: "Veröffentlichen",
        delete: "Löschen",
        upcoming: "Anstehende",
        past: "Vergangene",
        active: "Aktive",
        redeemed: "Entwertete",
        expired: "Abgelaufene",
        purchased_on: "",
        expires_on: "Läuft ab am",
        settings: "Einstellungen",
        rejected: "Abgelehnte",
        no_of_guests: "Gäste",
        date: "Datum",
        appointment: "Termin",
        date_time: "Wunschtermin",
        approve: "Bestätigen",
        reject: "Ablehnen",
        your_query: "Deine Anfrage",
        scan_qr: "QR Code scannen",
        sync_data: "Sync Daten",
        please_scan_qr: "Bitte QR scannen und den Deal anschließend entwerten",
        scan_qr_code: "QR Code scannen",
        enter_manually: "Manuell eingeben",
        pending_data: "Ausstehende Daten",
        sync_now: "Jetzt Sync",
        dashboard: "Dashboard",
        or: "oder",
        enter_qr_code: "Bitte QR Code eingeben",
        save: "Speichern",
        edit: "Bearbeiten",
        deal_redeemed_successully: "Deal erfolgreich gescannt",
        deal_code: "Deal Code",
        redeemed_on: "Entwertet am",
        no_data_to_sync: "Derzeit keine ausstehenden Daten",
        data_synced_successfully: "Daten wurden erfolgreich synchronisiert",
        bonus_cards: "Bonuspunkte",
        bonus_card_scanned_successfully: "Stempelkarte erfolgreich gescannt",
        invalid_code: "Ungültiger Code",
        pending_data_exists: "Du hast noch ausstehende Daten, bitte synchronisiere diese, bevor Du Dich abmeldest",
        holidays: "Meine Kapazität",
        delete_chat: "Löschen",
        sure_delete_chat: "Bist Du sicher, dass Du diesen Chat löschen willst?",
        no_records_found: "Derzeit keine Inhalte",
        filter_by_date: "Nach Datum ",
        choose_by_date: "Datum wählen",
        sure_delete_holiday: "Bist Du sicher, dass Du diesen Block löschen willst?",
        add_holiday: "Block hinzufügen",
        date_star: "Datum",
        from_time: "von",
        to_time: "bis",
        info: "Alle Zeiten",
        days_of_week: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
        event_schedule: "Veranstaltungskalender",
        this_deal_can_be_redeemed_on_dates: "Einlösezeiträume",
        from: "vom",
        statistics: "Statistik",
        redemption_dates: "Einlösezeiträume",
        until_stock_lasts: "Solange der Vorrat reicht",
        on_following_days: "immer an den folgenden Tagen:",
        this_deal_can_be_redeemed: "This deal can redeemed on/before:",
        details: "Details",
        conditions: "Konditionen",
        published: "Veröffentlicht",
        unpublished: "Offline",
        okay: "Okay",
        Saved: "Saved",
        Booked: "Buchungsanfragen",
        Checked_in: "Check-Ins",
        Reedemed: "Entwertete",
        Scanned: "Gescannte",
        Clicks: "Klicks",
        error_holiday_mandatory: "Bitte alle Pflichtfelder ausfüllen",
        error_holiday_from_less_than_to: "Die Startzeit muss vor der Endzeit beginnen",
        my_promotions: "Meine Promotions",
        pending: "Anfragen",
        guests: "Gäste",
        guest: "Gäste",
        deal: "Deal",
        deals: "Deals",
        no_upcoming_appointments: "Keine anstehenden Termine",
        no_past_appointments: "Keine vergangenen Termine",
        alternate_dates: "Alternativtermin",
        no_pending_appointments: "Derzeit keine Terminanfragen",
        no_rejected_appointments: "Keine abgelehnten Terminanfragen",
        guests_capital: "Gäste",
        deals_capital: "Deals",
        confirm_cancel_appointment: "Bist Du sicher, dass Du diesen Termin absagen willst?",
        time_star: "Zeit",
        error_appointment_future_date: "Bitte eine Zeit in der Zukunft auswählen",
        confirm_approve_appointment: "Bist Du sicher, dass Du diese Terminanfrage bestätigen möchtest?",
        confirm_reject_appointment: "Bist Du sicher, dass Du diese Terminanfrage ablehnen möchtest?",
        book: "Buchen",
        alternate_date: "Alternativtermin",
        alternate_time: "Alternative Zeit",
        no_of_deals: "Anzahl der Deals",
        sure_unpublish_product: "Bist Du sicher, dass Du diesen Inhalt offline setzen willst?",
        sure_publish_product: "Bist Du sicher, dass Du diesen Inhalt veröffentlichen willst?",
        promotional_period: "Gültigkeitszeiträume",
        error_holiday_from_time: "Bitte Startzeit wählen",
        error_holiday_date: "Bitte Datum wählen",
        error_holiday_future: "Startzeit muss in der Zukunft liegen",
        error_appointment_date: "Bitte Datum wählen ",
        error_appointment_time: "Bitte Startzeit wählen",
        no_hot_deals_found: "Derzeit keine Hot Deals",
        no_actions_found: "Derzeit keine Promotions",
        no_events_found: "Derzeit keine Events",
        full_day_off: "Ganzen Tag blockieren",
        confirm_delete_appointment: "Bist Du sicher, dass Du diesen Inhalt löschen willst?",
        full_day_off: "Ganzer Tag blockiert",
        product_draft_error: "Dieser Inhalt kann nicht ohne Bild/Preisliste veröffentlicht werden. Bitte lade ein Bild und/oder eine Preisliste hoch, bevor Du den Inhalt veröffentlichst",
        add_product: "",
        select_product: "Promotion/Event wählen",
        holiday_date: "Bitte Datum wählen",
        holiday_from_time: "Bitte Startzeit wählen",
        holiday_to_time: "Bitte Endzeit wählen",
        bonus_deals: "Bonus Deals",
        no_bonus_deals_found: "Derzeit keine Bonus Deals",
        available_till: "Verfügbar bis",
        scans_required: "Punkte benötigt",
        fcm_permission_required: "Erlaubnis für Pushnachrichten benötigt",
        notifications: "Benachrichtigungen",
        no_notifications_yet: "Derzeit keine Benachrichtigungen",
        confirm_delete_notification: "Bist Du sicher, dass Du diese Benachrichtigung löschen willst?",
        to: "bis",
        choose_time_suggested_by_user: "Bitte Terminbeginn innerhalb des vom User vorgeschlagenen Zeitfensters wählen",
        add_bonus_conditions: "Bitte füge Deinem Profil die Konditionen für Dein Bonusprogramm hinzu, bevor Du einen Bonus Deal veröffentlichst",
        edit_holiday: "Block aktualisieren",
        emp_login_not_allowed: "Kein Mitarbeiter-Login in der Unternehmerapp. Bitte melde Dich bei der Mitarbeiterapp an",
        clicks_on_info: "Klicks auf Infobutton",
        booking_requests: "Buchungsanfragen",
        clicks_on_call: "Klicks auf Anrufbutton",
        clicks_on_messenger: "Klicks auf Messenger",
        messages: "Nachrichten",
        redirect_to_website: "Weiterleitungen auf Deine Webseite",
        secured_deals: "Gesicherte",
        reset: "Zurücksetzen",
        search: "Suchen",
        you_have_new_messages_refresh: "Du hast eine neue Nachricht, bitte aktualisiere die App",
        for_what_content: "Welche Art von Anfragen möchtest Du blockieren?",
        block_opening_time: "Anfragen für den regulären Betrieb",
        block_products: "Anfragen für Promotions/Events",
        complete_block: "Alle Anfragen",
        ent_login_not_allowed: "Kein Unternehmer-Login in der Mitarbeiter-App möglich. Melde Dich in der Unternehmerapp an",
        send_push_message: "Pushnachricht senden?",
        send_push_to_fav_ent: "Pushnachricht an Deine Favoritenliste senden.",
        send_push_to_fav_product: "Pushnachricht an User senden, die diesen Inhalt auf ihre Merkliste gesetzt haben",
        capacity_type: "Art der Blockierung",
        choose: "Auswählen",
        predefined_slots: "Fixe Zeitslots",
        percent_discount: "% Rabatt",
        cancelled_by_you: "Von Dir abgesagt",
        cancelled_by_user: "Vom User abgesagt",
        regular_operation: "Regulärer Betrieb",
        your_data_belongs_to_you: "Deine Daten gehören dir und werden ausschließlich zur Bearbeitung deiner Anfrage verarbeitet. Mehr dazu erfährst du in unseren",
        info_on_data_protection: "Hinweisen zum Datenschutz",
        submit_request: "Stimme zu – Abschicken",
        desired_date: "Wunschtermin",
        name_of_location: "Name Deiner Location",
        approved_date: "Termin",
        confirm: "Bestätigen",
    }
});

export default strings