import LocalizedStrings from 'react-native-localization'

/**
 * Localization
 */
let strings = new LocalizedStrings({
    "en-US": {
        ok: "Ok",
        cancel: "Cancel",
        sign_in_as: "Sign in as",
        user: "User",
        entrepreneur: "Entrepreneur",
        skip: "Skip",
        emailId: "Email ID",
        password: "Password",
        forgotPassword: "Forgot Password?",
        conditions_our: "Our",
        terms_and_conditions: "Terms and Conditions",
        conditions_apply: "apply",
        conditions_the: "The",
        conditions_of_ent: "terms & conditions",
        conditions_ent_apply: "of the provider apply",
        i_agree_send_request: "I agree - Send request",
        by_choosing_this_option: "By continuing as guest or signing via social media, you agree to our",
        your_data_belongs_to_you: "Your Data belongs to you! Here you can find our",
        info_on_data_protection: "Information on data protection",
        sign_in: "Sign in",
        new_user: "New User?",
        are_you_entrepreneur: "Are you an entrepreneur?",
        contact_us: "Contact us",
        new_entrepreneur: "New Entrepreneur?",
        sign_up: "Sign up",
        proceed: "Proceed",
        i_agree_proceed: "I agree - Proceed",
        or_login_using: "or login using",
        facebook: "facebook",
        google: "google",
        mein_regensburg: "My Regensburg",
        book: "Book",
        locations: "Locations",
        favorites: "Favorites",
        my_area: "My Area",
        hot_deals: "Hot Deals",
        actions: "Gastro, Dienste & Co.",
        events: "Events, Workshops & Co.",
        view_all: "View All",
        messenger: "Messenger",
        my_hot_deals: "My Hot Deals",
        my_appointments: "My Appointments",
        settings: "Settings",
        profile: "Profile",
        permission_title: "Location Required",
        permission_message: "Please grant permission to continue.",
        permission_must: "App cannot work without Location, kindly grant permission in settings.",
        location_off: "Please turn on location and try again.",
        first_name: "First Name",
        last_name: "Last Name",
        confirm_password: "Confirm Password",
        male: "Male",
        female: "Female",
        other: "Other",
        mobile_number: "Mobile Number",
        back_to_login: "Back to sign in",
        back: "Back",
        asterisk: "*",
        internet_not_connected: "Internet not connected. Please check your network connection and try again later.",
        something_went_wrong: "There is connectivity issue at present, please try after sometime.",
        could_not_connect_server: "Could not connect to server, please try again later.",
        enter_email: "Please enter Email ID",
        invalid_email: "Please enter a valid Email ID",
        enter_password: "Please enter Password",
        enter_new_password: "Please enter new Password",
        accept_terms: "Please accept terms and conditions",
        left: "Left",
        just: "just",
        instead_of: "instead of",
        euro: "\u20AC",
        go_to_home: "Go to home",
        continue_as_guest: "Continue as guest",
        send_link: "Send link",
        send_otp: "Send OTP",
        sort_by_distance: "Sort by Distance",
        filter_by_date: "Sort by Date",
        read_more: "Read more",
        read_less: "Read less",
        message_book: "Message/Book",
        message: "Messenger",
        call: "Call",
        buy: "Buy",
        details_and_conditions: "Details & Conditions",
        deal_details_conditions: "Details & Conditions",
        action_details_conditions: "Details & Conditions",
        event_details_conditions: "Details & Conditions",
        bonus_details_conditions: "Details & Conditions",
        price_list: "Price list",
        done: "Done",
        business_name: "Business Name",
        address: "Address",
        enter_first_name: "Enter First name",
        enter_last_name: "Enter Last name",
        password_should_be: "Password should be minimum of 6 characters",
        enter_confirm_password: "Please enter Confirm Password",
        password_do_not_match: "Password and Confirm Password do not match",
        enter_mobile: "Enter Mobile number",
        mobile_should_be: "Mobile number should be minimum of 7 digits",
        enter_valid_mobile: "Please enter a valid mobile number",
        choose_gender: "Please choose gender",
        login_to_continue: "Please login to continue",
        receive_phone_notifications: "Receive Phone Notifications",
        delete_your_account: "Delete your account",
        from_blocally_fav_entrepreneurs: "From Blocally & favorite entrepreneurs",
        from_blocally_only: "Only from Blocally",
        change_password: "Change Password",
        language: "Language",
        sign_out: "Sign out",
        sure_logout_out: "Are you sure you want to logout?",
        yes: "Yes",
        no: "No",
        sure_delete_account: "Are you sure you want to delete your account?",
        action_cant_be_reversed: "(This action cannot be reversed)",
        enter_otp: "Enter OTP",
        submit: "Submit",
        verify: "Verify",
        verify_register: "Verify & Register",
        resend_otp: "Resend OTP",
        please_enter_otp: "Please enter OTP",
        otp_should_be: "OTP should be of 4 digits",
        incorrect_otp: "Incorrect OTP",
        old_password: "Old Password",
        new_password: "New Password",
        enter_old_password: "Please enter old password",
        enter_new_password: "Please enter new password",
        new_password_do_not_match: "New Password and Confirm Password do not match",
        reset_password: "Reset Password",
        password_changed_successfully: "Password changed successfully",
        menu_not_available: "Menu not available",
        english: "English",
        german: "German",
        still: "Still",
        enter_additional_info: "Please enter additional information to complete the login process",
        social_media_login: "Social Media Login",
        code: "Code",
        press_back_again_to_exit: "Press back again to exit",
        search: "Search",
        open: "Open",
        opening_hours: "Opening Hours",
        view_menu: "View Menu",
        action_events: "Promotions & Events",
        entrepreneurs: "Entrepreneurs",
        bookmarklist: "Bookmarklist",
        no_favorites_yet: "No favorites yet",
        you_are_about_to_purchase: "You are about to purchase a deal",
        more: "more",
        valid_till: "Valid till",
        amount_to_be_paid: "Amount to be paid",
        confirm_pay: "Confirm & Pay",
        active: "Active",
        redeemed: "Redeemed",
        expired: "Expired",
        purchased_on: "Purchased on",
        expiry_date: "Expiry Date",
        no_active_deals: "No bonus deals yet",
        no_redeemed_deals: "No redeemed deals yet",
        no_expired_deals: "No expired deals yet",
        purchase_date: "Purchase Date",
        proceed_to_redeem: "Proceed to Redeem",
        you_only_receive_benefit: "You only receive your benefit from the hotdeal of the provider personally by the 'validated button' was devalued.So did not cancel the hotdeal yourself.",
        certainly_invalidated_by_vendor: "Certainly invalidated by the vendor?",
        redeem: "Redeem",
        you_are_about_to_redeem: "You are about to redeem a deal",
        continue: "Continue",
        value: "Value",
        deal_redeemed_successfully: "Deal has been redeemed successfully",
        edit: "Edit",
        save: "Save",
        gender: "Gender",
        for_bookings_use_button: "For bookings use button only",
        appointment: "Appointment",
        date: "Date",
        no_of_guests: "No. of guests",
        approval_pending: "Approval Pending",
        approved: "Approved",
        rejected: "Rejected",
        send_appointment_request: "Send Appointment Request",
        please_indicate_desired_date: "Please indicate the desired date and time",
        you_can_suggest_alternate: "You can suggest an alternate date as well",
        please_tell_which_services: "Any special/addiotional notes for the provider?",
        note: "Note",
        your_name_will_be_shared: "Your name and contact number will be shared with the entrepreneur.",
        name: "Name",
        choose_date: "Choose Date",
        choose_time: "Choose Time",
        alternate_date: "Alternate Date",
        alternate_time: "Alternate Time",
        enter_name: "Please enter name",
        enter_date: "Please choose date for appointment",
        enter_time: "Please choose time for appointment",
        enter_num_of_guests: "Please enter number of guests",
        enter_valid_num_of_guests: "Please enter a correct number for number of guests",
        at_least_one_guest: "Number of guests should be at least 1",
        enter_comments: "Please enter which service is required",
        upcoming: "Upcoming",
        past: "Past",
        no_upcoming_appointments: "No upcoming appointments",
        no_past_appointments: "No past appointments",
        no_pending_appointments: "No pending appointments",
        no_rejected_appointments: "No rejected appointments",
        guests: "guests",
        search_category: "Search Category",
        search_entrepreneur: "Search Entrepreneur",
        imprint: "Imprint & legal",
        delete_chat: "Delete Chat",
        sure_delete_chat: "Are you sure you want to delete chat?",
        no_categories_found: "No categories found",
        add_nickname: "Add Nickname",
        you_can_opt_for_nick_name: "You can opt to start your chat with a nickname.",
        your_current_name: "Your current name is",
        continue_with_this_name: "Continue with this name",
        or_add_a_new: "Or add a new nickname.",
        save_and_use_nickname: "Save and use nickname",
        enter_nickname: "Please enter nickname",
        nickname: "Nickname",
        info: "All Dates",
        get_deal: "Get Deal",
        saved: "Saved",
        until_stock_lasts: "Until Stock Lasts",
        your_query: "Your Query",
        enter_business_name: "Enter your Business Name",
        you_are_interested_in_hot_deal: "Get the deal!",
        from: "From",
        deals_already_booked_cancelled: "deals have already been booked/cancelled.",
        deals_secured_by_other_locals: "deals are currently secured by other locals.",
        are_currently_available: "are currently available",
        you_now_have_following_options: "You now have the following options",
        secure_a_hot_deal: "Add to your hot deals",
        direct_booking: "Reserve",
        secure_hot_deal_paragraph: "Add the deal to your hot deals. If the deal is offered in a limited quantity, you can only redeem it as long as there are deals left. Under \"My Hot Deals\" you can track the availability of your added deals.",
        direct_booking_paragraph: "Some deals you can also reserve. Just select the deal you want to reserve when you make your booking request. If the entrepreneur confirms your booking request, the requested number of deals is also reserved for that day.",
        save_for: "Save for",
        this_deal_can_be_redeemed: "This deal can redeemed on/before:",
        on_following_days: "always on following days:",
        this_deal_can_be_redeemed_on_dates: "Redemption Periods",
        days_of_week: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        provider_has_limited: "The provider has limited the booking and redemption options of the deal to a maximum of",
        deals_within: "deals within",
        already_saved_booked_max: "days. You have already reached the maximum number for this period.",
        details: "Details",
        saved_on: "Saved on",
        redeemed_on: "Redeemed on",
        expired_on: "Expired on",
        appointment_date: "Appointment Date",
        unsave: "Unsave",
        scan_qr: "Scan QR",
        please_scan_qr: "Please scan the QR code to redeem the deal",
        scan_qr_code: "Scan QR code",
        or: "or",
        enter_manually: "Enter Manually",
        enter_qr_code: "Please enter QR code",
        hot_deal_redeem_success: "Hotdeal has successfully been redeemed. Show this screen to entrepreneur and get your service",
        redeemed_successfully: "Redeemed Successfully!",
        hot_deal_redeem_failed: "Oh! Something went wrong. Please make sure that you scanned the right code.",
        redemption_failed: "Redemption Failed!",
        redeem_on: "Redeem on",
        action_on: "Action on",
        event_detail: "Event Detail",
        the_deal: "The deal \"",
        deal_has_expired: "\" has expired",
        you_have_appointment_for_this: "You have an appointment booked for this deal.",
        event_schedule: "Event Schedule",
        visit_us_on: "Visit us on",
        no_records_found: "No records found",
        no_hot_deals_found: "No Hot Deals found",
        no_actions_found: "No Actions found",
        no_events_found: "No Events found",
        check_in: "Check In",
        you: "You",
        to: "To",
        choose_a_day: "Choose a Day",
        choose_alternate_day: "Alternate Day",
        add_one_more_date: "Add one more date",
        number_of_deals: "Number of deals",
        enter_from_time: "Please choose from time for appointment",
        enter_to_time: "Please choose to time for appointment",
        choose_alternate_date: "Please choose alternate date for appointment",
        choose_alternate_from_time: "Please choose alternate from time for appointment",
        choose_alternate_to_time: "Please choose alternate to time for appointment",
        both_date_time_cannot_be_same: "Both times cannot be same",
        to_time_should_be_big: "To time should be after from time",
        time_already_selected: "This date time is already selected",
        pending: "Pending",
        conditions: "Conditions",
        alternate_dates: "Alternate Dates",
        guest: "guest",
        date_time_should_be_in_future: "Appointment date time should be in future",
        choose_a_product: "Promotions & events",
        entrepreneur_on_holiday: "Entrepreneur is on holiday at this time",
        appointment_should_match_specific_date: "Appointment can be added only for specific dates",
        view_holiday_calendar: "View Holiday Calendar",
        entrepreneur_on_holiday_on_following: "Entrepreneur is on holidays on following dates",
        check_in_to_redeem: "Check in to redeem",
        booked: "Booked",
        deal: "deal",
        deals: "deals",
        no_booked_deals: "No booked deals yet",
        not_available: "Not Available",
        no_of_deals: "No. of deals",
        enter_no_of_deals_to_redeem: "For how many deals you want to check-in?",
        you_have_saved: "You have saved",
        enter_count: "Enter Count",
        enter_deal_count: "Please enter deal count",
        enter_valid_deal_count: "Please enter valid deal count",
        you_can_choose_max: "You can choose a maximum of",
        max_deals: "deals",
        checked_in: "Checked-in",
        sure_redeem_deal: "Are you sure you want to redeem this deal?",
        deal_redeemed_successully: "Deal redeemed successfully",
        deal_redeemed_failed: "Deal redemption failed",
        no_more_deals_left: "No more deals left",
        no_checked_in_deals: "No checked in deals yet",
        deal_not_found: "Deal not found",
        deal_can_be_redeemed_after: "This deal can be redeemed after ",
        bonus: "Bonus",
        qr_code: "QR Code",
        please_scan_the_qr_code: "Please scan the QR code",
        no_entrepreneurs_with_bonus: "No entrepreneurs with bonuses yet",
        bonus_deals: "Bonus Deals",
        avail_now: "Avail Now",
        not_sufficient_scans: "You do not have sufficient bonus scans",
        redemption_dates: "Redemption Periods",
        promotional_period: "Promotional Periods",
        closed: "Closed",
        about_us: "About Us",
        expires_on: "Expires on",
        guests_capital: "Guests",
        deals_capital: "Deals",
        confirm_cancel_appointment: "Are you sure you want to cancel appointment?",
        you_can_check_in_within: "To check-in, you must not be further than 100 meters from the provider",
        meters_radius: "meters radius only",
        deal_can_be_redeemed_between: "This deal can be redeemed between ",
        and: "and",
        reset: "Reset",
        in_case_of_any_queries: "In case of any queries or complaints, please feel free to contact us at",
        choose_at_least_one: "Please choose at least one deal",
        on_before: "on/before",
        scans_required: "scans required",
        this_deal_requires: "This bonus deal requires",
        scans: "scans",
        you_currently_have: "You currently have",
        sure_avail_bonus: "Are you sure you want to avail this bonus deal?",
        scans_available: "scans available",
        final_redeem: "Finally Redeem",
        booked_on: "Booked on",
        enter_number_of_deals: "Please enter number of deals",
        enter_valid_number_of_deals: "Please enter valid number of deals",
        deals_should_be_less_than: "Max 1000 deals can be booked",
        deal_cannot_be_checked_in: "Deal cannot be checked in",
        until: "until",
        save_deal: "Add to my hot deals",
        reserve: "Reserve",
        available_till: "Available till...",
        valid_for_one_year: "After you have secured the bonus deal, it is valid for one year!",
        deal_cannot_be_saved: "This deal can no longer be saved/booked",
        direct_booking_not_available: "Direct Booking is not available",
        expires: "Expires",
        deal_added: "Deal Added",
        as_long_as_available: "As long as there are deals left, you can check in at the provider's place within the redemption period to redeem the deal",
        please_tell_provider: "Please tell the provider when ordering that you want to redeem a Hot Deal.",
        no_network_at_provider: "No network at the provider's place?",
        no_problem_check_in: "No problem! You can check in within a radius of 100 m. After check-in the deal is also available offline for redemption.",
        limited_number_of_deals: "Limited number of Deals",
        limited_deals_detail: "This deal is only offered in a limited number. You can only redeem the deal as long as there  are still remaining deals left.",
        bonus_info_heading: "Bonus info heading",
        bonsu_info_detail: "Bonus info detail",
        booked_info_heading: "Bonus info heading",
        booked_info_detail: "Bonus info detail",
        as_long_as_stock_lasts: "As long as stock/capacity lasts",
        unlimited_detail: "The number of deals offered is not limited. Deals can be redeemed at the redemption periods as long as  the provider still has the offered products in stock or still has the capacity to provide the offered service.",
        check_in_failed: "Check-in failed!",
        you_can_only_check_in: "You can only check in to redeem the deal during the following redemption periods:",
        added: "Added",
        reserved: "Reserved",
        deal_request_sent: "Request has been sent",
        deal_request_detail: "If your booking request is confirmed, you can check in at the provider on the day of your appointment and redeem the reserved deal.",
        provider: "Provider",
        my_card: "My Card",
        check_in_successful: "Check-in successful",
        press_redeem_and_show: "Press ‚Äûredeem‚ Äú and show the screen to the provider so that he can redeem the deal.",
        terms_and_conditions_of_provider: "Terms and Conditions of the provider",
        closed_blocked_for_booking: "= closed/blocked for booking requests",
        request_possible: "= Request possible/Provider will check availability",
        guide: "Guide",
        guide_for_booking: "Guide for the booking request",
        if_you_are_flexible: "If you are flexible in terms of time, you can also select the time slot in which the provider can set the start of the appointment",
        for_example_if_you: "For example, if you select a time period between 8:00 - 10:00, the provider can confirm the start of the appointment for 09:30. This makes it easier for the provider to schedule the appointment and increases the chance that the provider will find a free appointment for you.",
        if_your_appointment: "If your appointment should start at a certain time, you can of course choose only this one.",
        fcm_permission_required: "Permission required to receive Push Notifications",
        notifications: "Notifications",
        no_notifications_yet: "No notifications yet",
        confirm_delete_notification: "Are you sure you want to delete this notification?",
        dont_show_me_again: "Don't show me again",
        bonus_added: "Bonus Added",
        for_one_year: "This bonus deal can be redeemed within one year",
        please_tell_provider_bonus: "Please tell the provider when ordering that you want to redeem a Bonus Deal.",
        you_have_made_appointment: "You have made an appointment for",
        check_in_30_min_before: "Please note that you can check in only 60 minutes before the appointment.",
        url_not_available: "Website URL is not available",
        product_has_expired: "This product has expired and cannot be checked in",
        opens: "Opens",
        at: "",
        closed_now: "Closed Now",
        you_have_new_messages_refresh: "You have got new message, please refresh",
        currently_only_times_are_displayed: "Currently only times are displayed in which the promotion/event you have chosen is valid.",
        confirm_delete_appointment: "Are you sure you want to delete this appointment?",
        confirm_delete_deal: "Are you sure you want to delete this deal?",
        saved_expires: "Order the deal until",
        booked_expires: "Appointment on",
        bonus_expires: "Bonus Deal valid until",
        choose_both_start_end: "Please choose both start and end times",
        filter: "Filter",
        percent_discount: "% discount",
        cancelled_by_you: "Cancelled by You",
        cancelled_by_ent: "Cancelled by Entrepreneur",
        submit_request: "Submit Request",
        phone_number: "Phone Number",
        no_favorite_products_yet: "Currently no promotions / events on your watchlist",
        find_inquiries_in_my_appointments: "Your inquiries and You can find dates in your area under \"My appointments\"",
        no_time_left_to_choose: "All the times have already passed",
        choose_one_product_must: "Choose a product:",
        booking_request: "Booking Request",
        terms_of_service: "Terms of Service",
        no_chats_yet: "You currently have no ongoing chats",
        bonus_deal_not_offered: "The provider does not currently offer a bonus deal",
        from_2: "From",
        ent_gdpr_text: "Your data is yours and will only be used to process your request. You can find out more about this in our",
        ent_gdpr_link: "information on data protection",
        no_bonus_deals: "Currently no bonus deal available",
        mandatory_to_choose_product: "This provider only accepts booking requests for promotions / events - please select one.",
        optional_b: "(optional):",
        desired_date: "Desired Date",
        approved_date: "Meeting",
        checked_in_deals_are_there: "You have checked in some deals, if you logout you will loose those deals. Are you sure you want to continue?",
        enter_no_of_deals_to_check_in: "Enter the number of deals to check-in",
        otp_sent_on_mail: "A otp has been sent to youe email address. Please also check your spam folder.",
    },
    "de": {
        Ok: "Ok",
        cancel: "Absagen",
        sign_in_as: "Als anmelden",
        user: "User",
        entrepreneur: "Anbieter",
        skip: "Überspringen",
        emailId: "E-Mail-Adresse",
        password: "Passwort",
        forgotPassword: "Passwort vergessen?",
        conditions_our: "Es gelten unsere",
        terms_and_conditions: "Allgemeinen Geschäftsbedingungen",
        conditions_apply: "",
        conditions_the: "Es gelten die",
        conditions_of_ent: "Buchungskonditionen & Hinweise",
        conditions_ent_apply: "des Anbieters",
        i_agree_send_request: "Ich stimme zu - Abschicken",
        by_choosing_this_option: "Indem du dich anmeldest oder als Gast fortfährst, akzeptierst du unsere",
        your_data_belongs_to_you: "Deine Daten gehören dir! Hier findest du unsere",
        info_on_data_protection: "Hinweise zum Datenschutz",
        sign_in: "Anmelden",
        new_user: "Neu hier?",
        are_you_entrepreneur: "Du bist Unternehmer?",
        contact_us: "Kontaktiere uns",
        new_entrepreneur: "",
        sign_up: "Registrieren",
        proceed: "Fortfahren",
        i_agree_proceed: "Ich stimme zu – Fortfahren",
        or_login_using: "oder anmelden mit",
        facebook: "Facebook",
        google: "Google",
        mein_regensburg: "Mein Regensburg",
        book: "Buchen",
        locations: "Locations",
        favorites: "Favoriten",
        my_area: "Mein Bereich",
        hot_deals: "Hot Deals",
        actions: "Gastro, Dienste & Co.",
        events: "Events, Workshops & Co.",
        view_all: "Mehr",
        messenger: "Messenger",
        my_hot_deals: "Meine Hot Deals",
        my_appointments: "Meine Termine",
        settings: "Einstellungen",
        profile: "Profil",
        permission_title: "Standort benötigt",
        permission_message: "Bitte Erlaubnis erteilen, um fortzufahren",
        permission_must: "Die B LOCALLY App zeigt dir alle Inhalte sortiert nach Entfernung und Zeit an und benötigt daher deinen Standort. Bitte Erlaubnis in den Einstellungen erteilen.",
        location_off: "Bitte Standort aktivieren und erneut versuchen",
        first_name: "Vorname",
        last_name: "Nachname",
        confirm_password: "Passwort bestätigen",
        male: "Männlich",
        female: "Weiblich",
        other: "Divers",
        mobile_number: "Mobilfunknummer",
        back_to_login: "Zur Anmeldung",
        back: "Zurück",
        asterisk: "*",
        internet_not_connected: "Keine Internetverbindung. Bitte überprüfe deine Netzwerkverbindung und versuche es erneut.",
        something_went_wrong: "Verbindungsproblem! Bitte versuche es (später) erneut.",
        could_not_connect_server: "Keine Verbindung zum Server möglich. Bitte versuche es (später) erneut.",
        enter_email: "Bitte E-Mail-Adresse angeben",
        invalid_email: "Bitte eine gültige E-Mail-Adresse angeben",
        enter_password: "Bitte Passwort eingeben",
        enter_new_password: "Bitte neues Passwort eingeben",
        accept_terms: "Bitte akzeptiere die Buchungskonditionen & Hinweise des Anbieters",
        left: "übrig",
        just: "nur",
        instead_of: "anstatt",
        euro: "\u20AC",
        go_to_home: "Appeinblick",
        continue_as_guest: "Als Gast fortfahren",
        send_link: "Link senden",
        send_otp: "Einmal-Passwort senden",
        sort_by_distance: "Nach Entfernung",
        filter_by_date: "Nach Datum",
        read_more: "mehr",
        read_less: "weniger",
        message_book: "Message/Book",
        message: "Messenger",
        call: "Anrufen",
        buy: "Kaufen",
        details_and_conditions: "Details & Konditionen",
        deal_details_conditions: "Details & Konditionen",
        action_details_conditions: "Details & Konditionen",
        event_details_conditions: "Details & Konditionen",
        bonus_details_conditions: "Details & Konditionen",
        price_list: "Preisliste",
        done: "Fertig",
        business_name: "Firmenname",
        address: "Adresse",
        enter_first_name: "Bitte Vornamen angeben",
        enter_last_name: "Bitte Nachnamen angeben",
        password_should_be: "Passwort muss mindestens 6 Zeichen enthalten",
        enter_confirm_password: "Bitte Passwort bestätigen",
        password_do_not_match: "Passwörter stimmen nicht überein",
        enter_mobile: "Mobilfunknummer angeben",
        mobile_should_be: "Mobilfunknummer muss mindestens 7 Ziffern enthalten",
        enter_valid_mobile: "Bitte eine gültige Mobilfunknummer angeben",
        choose_gender: "Bitte Geschlecht wählen",
        login_to_continue: "Für dieses Feature ist eine Anmeldung erforderlich. Zurück zur Anmeldung?",
        receive_phone_notifications: "Pushnachrichten aktivieren",
        delete_your_account: "Account löschen",
        from_blocally_fav_entrepreneurs: "Von B LOCALLY und Favoriten/Merkliste",
        from_blocally_only: "Nur von B LOCALLY",
        change_password: "Passwort ändern",
        language: "Sprache",
        sign_out: "Abmelden",
        sure_logout_out: "Bist du sicher, dass du dich abmelden willst?",
        yes: "Ja",
        no: "Nein",
        sure_delete_account: "Bist du sicher, dass du deinen Account löschen willst?",
        action_cant_be_reversed: "Die Löschung deines Accounts kann nicht mehr rückgängig gemacht werden.",
        enter_otp: "Einmal-Passwort eingeben",
        submit: "Abschicken",
        verify: "Verifizieren",
        verify_register: "Verifizieren und registrieren",
        resend_otp: "Einmal-Passwort erneut senden",
        please_enter_otp: "Bitte Einmal-Passwort eingeben",
        otp_should_be: "Einmal-Passwort hat mindestens 4 Zeichen",
        incorrect_otp: "Falsches Einmal-Passwort",
        old_password: "Altes Passwort",
        new_password: "Neues Passwort",
        enter_old_password: "Bitte altes Passwort eingeben",
        enter_new_password: "Bitte neues Passwort eingeben",
        new_password_do_not_match: "Passwörter stimmen nicht überein",
        reset_password: "Passwort ändern",
        password_changed_successfully: "Passwort wurde erfolgreich geändert",
        menu_not_available: "Keine Preisliste vorhanden",
        english: "Englisch",
        german: "Deutsch",
        still: "noch",
        enter_additional_info: "Bitte alle Pflichtfelder ausfüllen, um fortzufahren",
        social_media_login: "Social Media Login",
        code: "Vorwahl",
        press_back_again_to_exit: "Zum Verlassen auf \"zurück\" drücken",
        search: "Suchen",
        open: "Geöffnet",
        opening_hours: "Öffnungszeiten",
        view_menu: "Preisliste anzeigen",
        action_events: "Promotions & Events",
        entrepreneurs: "Anbieter",
        bookmarklist: "Merkliste",
        no_favorites_yet: "Derzeit keine Anbieter als Favorit markiert",
        you_are_about_to_purchase: "",
        more: "mehr",
        valid_till: "Gültig bis",
        amount_to_be_paid: "",
        confirm_pay: "",
        active: "Checked-in",
        redeemed: "Entwertet",
        expired: "Abgelaufen",
        purchased_on: "",
        expiry_date: "Ablaufdatum",
        no_active_deals: "Derzeit keine Bonus Deals  - sammle Punkte bei den Anbietern und sichere dir deine Bonus Deals",
        no_redeemed_deals: "Noch keine Deals entwertet",
        no_expired_deals: "Noch keine Deals abgelaufen",
        purchase_date: "",
        proceed_to_redeem: "Mit der Entwertung fortfahren",
        you_only_receive_benefit: "",
        certainly_invalidated_by_vendor: "Deal sicher entgültig entwerten?",
        redeem: "Einlösen",
        you_are_about_to_redeem: "Du bist dabei, einen Hot Deal zu entwerten",
        continue: "Fortfahren",
        value: "Wert",
        deal_redeemed_successfully: "Hot Deal wurde erfolgreich entwertet",
        edit: "Bearbeiten",
        save: "Speichern",
        gender: "Geschlecht",
        for_bookings_use_button: "Für Buchungsanfragen bitte Buchungsmaske nutzen",
        appointment: "Termin",
        date: "Datum",
        no_of_guests: "Anzahl der Gäste",
        approval_pending: "Angefragt",
        approved: "Bestätigt",
        rejected: "Abgelehnt",
        send_appointment_request: "Ich stimme zu - Abschicken",
        please_indicate_desired_date: "Bitte Datum & Zeitfenster für  den  Terminbeginn  wählen",
        you_can_suggest_alternate: "Du kannst auch mehrere Alternativtermine vorschlagen",
        please_tell_which_services: "Was kann der Anbieter für dich tun?/ Anmerkungen",
        note: "Hinweis",
        your_name_will_be_shared: "",
        name: "Name",
        choose_date: "Datum wählen",
        choose_time: "Zeitfenster",
        alternate_date: "Alternativtermin",
        alternate_time: "Alternativer Zeitpunkt/Zeitraum",
        enter_name: "Bitte Vor- und Nachnamen angeben",
        enter_date: "Bitte ein Datum wählen",
        enter_time: "Bitte Zeitfenster wählen",
        enter_num_of_guests: "Bitte gib die Anzahl der Gäste an",
        enter_valid_num_of_guests: "Bitte gib eine gültige Anzahl der Gäste an",
        at_least_one_guest: "Anzahl der Gäste/Kunden muss mindestens 1 sein",
        enter_comments: "",
        upcoming: "Anstehende",
        past: "Vergangene",
        no_upcoming_appointments: "Derzeit stehen keine Termine an",
        no_past_appointments: "Noch keine vergangenen Termine",
        no_pending_appointments: "Derzeit keine laufenden Buchungsanfragen",
        no_rejected_appointments: "Noch keine abgelehnten Buchungsanfragen",
        guests: "Gäste",
        search_category: "",
        search_entrepreneur: "",
        imprint: "Impressum & Hinweise",
        delete_chat: "Chat löschen",
        sure_delete_chat: "Bist du sicher, dass du diesen Chat löschen willst?",
        no_categories_found: "Derzeit keine Kategorien verfügbar",
        add_nickname: "",
        you_can_opt_for_nick_name: "",
        your_current_name: "",
        continue_with_this_name: "",
        or_add_a_new: "",
        save_and_use_nickname: "",
        enter_nickname: "",
        nickname: "",
        info: "Alle Zeiten ",
        get_deal: "Hol dir den Deal",
        saved: "",
        until_stock_lasts: "Solange der Vorrat reicht",
        your_query: "Deine Anfrage",
        enter_business_name: "Firmenname angeben",
        you_are_interested_in_hot_deal: "Hol dir den Deal!",
        from: "vom",
        deals_already_booked_cancelled: "",
        deals_secured_by_other_locals: "",
        are_currently_available: "",
        you_now_have_following_options: "Du hast nun folgende Optionen",
        secure_a_hot_deal: "Zum Einlösen beim Anbieter einchecken",
        direct_booking: "Reserviere den Deal",
        secure_hot_deal_paragraph: "Du kannst innerhalb eines Radius von 100 Metern beim Anbieter einchecken, um den Deal einzulösen. Kein Netz beim Anbieter? Kein Problem! Einmal eingecheckt, ist der Deal auch offline verfügbar. Bitte informiere den Anbieter bei Bestellung, dass du einen Deal einlösen möchtest.",
        direct_booking_paragraph: "Manche Deals kannst du dir auch mit einer Reservierung sichern. Schicke dem Anbieter dazu eine Buchungsanfrage und wähle dabei die Anzahl der Deals aus, die du reservieren möchtest. Sobald der Anbieter deine Anfrage bestätigt hat, ist auch die von dir gewünschte Anzahl der Deals für diesen Termin reserviert. ",
        save_for: "",
        this_deal_can_be_redeemed: "",
        on_following_days: "immer an folgenden Tagen:",
        this_deal_can_be_redeemed_on_dates: "Einlösezeiträume",
        days_of_week: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
        provider_has_limited: "Der Anbieter hat die Einlösemöglichkeiten des Deals auf maximal",
        deals_within: "Deal/s innerhalb von",
        already_saved_booked_max: "Tag/en beschränkt. Du hast die maximale Anzahl für diesen Zeitraum bereits erreicht.",
        details: "Details",
        saved_on: "Gesichert am",
        redeemed_on: "Entwertet am",
        expired_on: "Abgelaufen am",
        appointment_date: "Termin",
        unsave: "",
        scan_qr: "QR Code scannen",
        please_scan_qr: "Bitte Deal vom Anbieter entwerten lassen",
        scan_qr_code: "QR Code scannen",
        or: "oder",
        enter_manually: "Manuell eingeben",
        enter_qr_code: "",
        hot_deal_redeem_success: "Deal erfolgreich entwertet",
        redeemed_successfully: "Deal wurde erfolgreich entwertet",
        hot_deal_redeem_failed: "Entwertung des Deals fehlgeschlagen",
        redemption_failed: "Entwertung des Deals fehlgeschlagen",
        redeem_on: "",
        action_on: "",
        event_detail: "",
        the_deal: "Der Deal \"",
        deal_has_expired: "\" ist abgelaufen",
        you_have_appointment_for_this: "Du hast diesen Deal reserviert",
        event_schedule: "Veranstaltungskalender",
        visit_us_on: "Besuche uns auf unserer Webseite",
        no_records_found: "Keine Inhalte gefunden",
        no_hot_deals_found: "Derzeit keine Hot Deals - Stay tuned!",
        no_actions_found: "Derzeit keine Promotions - Stay tuned!",
        no_events_found: "Derzeit keine Events - Stay tuned!",
        check_in: "Check-in",
        you: "Du",
        to: "bis",
        choose_a_day: "Datum wählen",
        choose_alternate_day: "Datum wählen",
        add_one_more_date: "Alternativtermin hinzufügen",
        number_of_deals: "Anzahl der Hot Deals",
        enter_from_time: "Bitte Zeitfenster für den Terminbeginn angeben: von/bis",
        enter_to_time: "Bitte Zeitfenster für den Terminbeginn angeben: von/bis",
        choose_alternate_date: "Bitte Datum für den Alternativtermin wählen",
        choose_alternate_from_time: "Bitte Zeitfenster für den Alternativtermin angeben. Von/Bis",
        choose_alternate_to_time: "Bitte Zeitfenster für den Alternativtermin angeben. Von/Bis",
        both_date_time_cannot_be_same: "Für Alternativtermine müssen unterschiedliche Zeiten vorgeschlagen werden",
        to_time_should_be_big: "Ende des Zeitfensters muss nach dem Beginn des Zeitfensters sein",
        time_already_selected: "Dieses Datum/Uhrzeit wurde bereits ausgewählt",
        pending: "Angefragt",
        conditions: "Konditionen",
        alternate_dates: "Alternativtermin",
        guest: "Gast",
        date_time_should_be_in_future: "Der Termin muss in der Zukunft liegen",
        choose_a_product: "Promotions & Veranstaltungen",
        entrepreneur_on_holiday: "",
        appointment_should_match_specific_date: "",
        view_holiday_calendar: "",
        entrepreneur_on_holiday_on_following: "",
        check_in_to_redeem: "",
        booked: "Gebucht",
        deal: "Deal",
        deals: "Deals",
        no_booked_deals: "Derzeit keine Deals gebucht",
        not_available: "Nicht verfügbar",
        no_of_deals: "Anzahl der Deals",
        enter_no_of_deals_to_redeem: "Für wie viele Deals möchtest du einchecken? Bitte gib hier die genaue Anzahl der Deals ein, die du beim Anbieter einlösen möchtest. ",
        you_have_saved: "",
        enter_count: "Anzahl angeben",
        enter_deal_count: "Bitte gib die Anzahl der Deals an, die du reservieren willst",
        enter_valid_deal_count: "Bitte gib eine gültige Anzahl der zu reservierenden Deals an",
        you_can_choose_max: "Du kannst maximal",
        max_deals: "Deals wählen",
        checked_in: "Checked-in",
        sure_redeem_deal: "Bist du sicher, dass du diesen Deal entwerten möchtest?",
        deal_redeemed_successully: "Der Hot Deal wurde erfolgreich entwertet",
        deal_redeemed_failed: "Entwertung fehlgeschlagen",
        no_more_deals_left: "Keine Deals mehr übrig",
        no_checked_in_deals: "Derzeit für keinen Deal eingecheckt",
        deal_not_found: "Deal nicht gefunden",
        deal_can_be_redeemed_after: "Dieser Deal kann zu folgenden Zeiten eingelöst werden",
        bonus: "Bonus",
        qr_code: "QR Code ",
        please_scan_the_qr_code: "Bitte lasse den QR Code scannen",
        no_entrepreneurs_with_bonus: "Derzeit keine Anbieter mit einem Bonusprogramm - stay tunded!",
        bonus_deals: "Bonus Deals",
        avail_now: "Bonus Deal sichern",
        not_sufficient_scans: "Du hast nicht genügend Punkte beim Anbieter gesammelt, um diesen Bonus Deal zu sichern.",
        redemption_dates: "Einlösezeiträume",
        promotional_period: "Gültigkeitszeiträume",
        closed: "Geschlossen",
        about_us: "Über uns",
        expires_on: "Läuft ab am",
        guests_capital: "Gäste",
        deals_capital: "Deals",
        confirm_cancel_appointment: "Bist du sicher, dass du diesen Termin absagen möchtest?",
        you_can_check_in_within: "Für den Check-in darfst du dich nicht weiter als 100 Meter vom Anbieter entfernt befinden",
        meters_radius: "",
        deal_can_be_redeemed_between: "",
        and: "",
        reset: "Löschen",
        in_case_of_any_queries: "",
        choose_at_least_one: "Bitte wähle mindestens einen Deal aus",
        on_before: "",
        scans_required: "Punkte benötigt",
        this_deal_requires: "Dieser Bonus Deal benötigt",
        scans: "Punkte",
        you_currently_have: "Derzeit hast Du",
        sure_avail_bonus: "Bist du sicher, dass du diesen Bonus Deal sichern möchtest?",
        scans_available: "Verfügbare Punkte",
        final_redeem: "Entwerten",
        booked_on: "Gebucht am",
        enter_number_of_deals: "Bitte Anzahl der Deals angeben",
        enter_valid_number_of_deals: "Bitte eine gültige Anzahl der Deals angeben",
        deals_should_be_less_than: "Bei diesem Anbieter können maximal 1000 Deals reserviert werden",
        deal_cannot_be_checked_in: "Du kannst (noch) nicht für diesen Deal einchecken",
        until: "bis",
        save_deal: "Zu meinen Hot Deals hinzufügen",
        reserve: "Reservieren",
        available_till: "Verfügbar bis",
        valid_for_one_year: "Nachdem du dir den Bonus Deal gesichert hast, ist er ein Jahr gültig!",
        deal_cannot_be_saved: "Dieser Deal kann nicht mehr gesichert/gebucht werden",
        direct_booking_not_available: "Bitte wähle ein(e) Promotion/Event",
        expires: "Läuft ab",
        deal_added: "Hot Deal hinzugefügt",
        as_long_as_available: "",
        please_tell_provider: "Bitte informiere den Anbieter bei deiner Bestellung, dass du einen Hot Deal einlösen möchtest.",
        no_network_at_provider: "Kein Internet beim Anbieter? ",
        no_problem_check_in: "Kein Problem! Du kannst innerhalb eines Radius von 100 Metern beim Anbieter einchecken. Nach dem Check-in ist der Deal auch offline zur Einlösung verfügbar.",
        limited_number_of_deals: "",
        limited_deals_detail: "",
        bonus_info_heading: "",
        bonus_info_detail: "",
        booked_info_heading: "",
        booked_info_detail: "",
        as_long_as_stock_lasts: "Solange der Vorrat reicht",
        unlimited_detail: "",
        check_in_failed: "Check-in fehlgeschlagen!",
        you_can_only_check_in: "Um den Deal einzulösen, kannst du nur innerhalb der Einlösezeiträume beim Anbieter einchecken. Diese sind:",
        added: "",
        reserved: "Reserviert",
        deal_request_sent: "Anfrage wurde versendet",
        deal_request_detail: "Wenn deine Buchungsanfrage bestätigt wird, kannst du am Tag deines Termins beim Anbieter einchecken und den Deal einlösen. Deine Anfragen und Termine findest du in deinem Bereich unter \"Meine Termine\".",
        provider: "Anbieter",
        my_card: "Meine Karte",
        check_in_successful: "Check-in erfolgreich",
        press_redeem_and_show: "Drücke auf \"Einlösen\" und lass den Deal anschließend vom Anbieter entwerten",
        terms_and_conditions_of_provider: "Buchungskonditionen und Hinweise des Anbieters",
        closed_blocked_for_booking: "geschlossen/für Anfragen blockiert",
        request_possible: "Anfrage möglich/Anbieter prüft Verfügbarkeit",
        guide: "Anleitung",
        guide_for_booking: "Wähle ein Zeitfenster",
        if_you_are_flexible: "Gib ein Zeitfenster an, in dem der Termin beginnen kann. Wähle dazu aus, wann der Termin frühestens und wann der Termin spätestens starten kann. Der Anbieter wird den Terminbeginn innerhalb des von dir vorgeschlagenen Zeitfensters bestätigen.",
        for_example_if_you: "Beispielsweise kannst du ein Zeitfenster zwischen 08:00 – 08:20 Uhr wählen. Hier könnte der Anbieter den Terminbeginn z.B. für 08:15 Uhr bestätigen. Wenn du zeitlich flexibel bist, kannst du auch ein großzügiges Zeitfenster anbieten, um dem Anbieter mehr Spielraum bei der Terminplanung zu geben.",
        if_your_appointment: "",
        fcm_permission_required: "Erlaubnis für Pushbenachrichtigungen benötigt",
        notifications: "Benachrichtigungen",
        no_notifications_yet: "Derzeit keine Benachrichtigungen",
        confirm_delete_notification: "Bist du sicher, dass du diese Benachrichtigung löschen willst?",
        dont_show_me_again: "Nicht mehr anzeigen",
        bonus_added: "Bonus Deal gesichert",
        for_one_year: "Dieser Bonus Deal kann innerhalb eines Jahres eingelöst werden",
        please_tell_provider_bonus: "Bitte informiere den Anbieter bei deiner Bestellung, dass du einen Bonus Deal einlösen möchtest",
        you_have_made_appointment: "Du hast diesen Deal reserviert. Terminbeginn:",
        check_in_30_min_before: "Bitte beachte, dass du frühestens 60 Minuten vor Terminbeginn beim Anbieter einchecken kannst.",
        url_not_available: " URL nicht gefunden",
        product_has_expired: "Dieser Deal ist abgelaufen - Check-in nicht möglich",
        opens: "Öffnet:",
        at: "",
        closed_now: "Geschlossen",
        you_have_new_messages_refresh: "You have got new message, please refresh",
        currently_only_times_are_displayed: "Es werden gerade nur Zeiten angezeigt, in denen die von dir gewählte Promotion/Veranstaltung gültig ist.",
        confirm_delete_appointment: "Bist du sicher, dass du diesen Termin löschen willst?",
        confirm_delete_deal: "Bist du sicher, dass du diesen Deal löschen willst?",
        saved_expires: "Bestelle den Deal bis zum",
        booked_expires: "Termin am",
        bonus_expires: "Bonus Deal gültig bis",
        choose_both_start_end: "Gib ein Zeitfenster an, in dem der Termin beginnen kann. Wähle dazu aus, wann der Termin frühestens und wann der Termin spätestens starten kann",
        filter: "Filter",
        percent_discount: "% Rabatt",
        cancelled_by_you: "von dir abgesagt",
        cancelled_by_ent: "vom Anbieter abgesagt",
        submit_request: "Stimme zu – Abschicken",
        phone_number: "Telefonnummer",
        no_favorite_products_yet: "Derzeit keine Promotions/Veranstaltungen auf deiner Merkliste",
        find_inquiries_in_my_appointments: "Deine laufenden Anfragen und bestätigten Termine findest du in deinem Bereich unter „Meine Termine“.",
        no_time_left_to_choose: "Die Termine für heute sind leider schon abgelaufen.",
        choose_one_product_must: "Wähle eine Promotion/Veranstaltung:",
        booking_request: "Buchungsanfrage",
        terms_of_service: "Allgemeine Geschäftsbedingungen",
        no_chats_yet: "Du hast derzeit keine laufenden Chats",
        bonus_deal_not_offered: "Derzeit bietet der Anbieter keinen Bonus Deal an",
        from_2: "von",
        ent_gdpr_text: "Deine Daten gehören dir und werden ausschließlich zur Bearbeitung deiner Anfrage verarbeitet. Mehr dazu erfährst du in unseren",
        ent_gdpr_link: "Hinweisen zum Datenschutz",
        no_bonus_deals: "Derzeit kein Bonus Deal verfügbar",
        mandatory_to_choose_product: "Dieser Anbieter nimmt nur Buchungsanfragen für Promotions/Veranstaltungen an – bitte wähle eine aus.",
        optional_b: "(optional):",
        desired_date: "Wunschtermin",
        approved_date: "Termin",
        checked_in_deals_are_there: "Du hast für einen oder mehrere Deals eingecheckt ohne sie zu entwerten - die Deals gehen verloren, wenn du dich jetzt abmeldest. Sicher abmelden?",
        enter_no_of_deals_to_check_in: "Enter the number of deals to check-in",
        otp_sent_on_mail: "Ein Einmal-Passwort wurde an Deine E-Mail-Adresse gesendet. Bitte checke auch Deinen Spam-Ordner."
    }
});

export default strings